set -g base-index 1 # start windows numbering at 1
set -s escape-time 0 # faster command sequences
bind -n C-q next-window
bind -n C-` select-pane -t :.+

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
